name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 167.172.87.166
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          /root/frontend_deploy.sh
